version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: hospital-management-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hospital-management-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    container_name: hospital-management-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: hospital-management-db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: SYSTEM
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  postgres_data:
    driver: local
  mysql_data:
    driver: local